{% set name = "readchar" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/magmax/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c5a1d5c6c22a6a59b76786a6d6731d5dcde168a105704f5ff7dca6a959e07275

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - flake8
  run:
    - python

test:
  imports:
    - readchar

about:
  home: https://github.com/magmax/python-readchar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to easily read single chars and key strokes.

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - rluria14
